### PR TITLE
Simplify Nix expressions

### PR DESCRIPTION
**Pull request by limeytexan**
- move darwin version of cargo-tarpaulin expression to edits directory
- add cargo-tarpaulin input for Linux

### CODE REVIEW

**Comment by etorreborre** [comment]
Thanks for the refactoring!

**Comment by etorreborre** [comment]
@limeytexan I had to do this to be able to start `flox develop`
```
{ self,
  inputs,
  ...
}
let
  cargo-tarpaulin-develop =
    if hostPlatform.isDarwin then
      callPackage ./cargo-tarpaulin-darwin.nix {
         inputs = inputs;
       }
    else cargo-tarpaulin;
```
Otherwise I was getting 
```
error: Function called without required argument "inputs" at /nix/store/y4inzgspfipz4vnv4y95q3sn28rcj6jq-source/pkgs/edits/cargo-tarpaulin-darwin.nix:1, did you mean "xinput"?
```
Is that correct?

**Comment by limeytexan** [comment]
Ah ... my apologies! I tested on Linux but forgot to circle back to Darwin, and yes I forgot to include the mandatory inputs. Well done for coming up with the right fix! The only other thing I'd say is it's slightly preferred to use "inherit" in that case, like this:
```
  cargo-tarpaulin-develop =
    if hostPlatform.isDarwin then
      callPackage ./cargo-tarpaulin-darwin.nix { inherit inputs; }
    else cargo-tarpaulin;
```

**Comment by etorreborre** [comment]
Good, I'm starting to have some intuition for nix :-)

**Pull request merged**
